#!/usr/bin/env python3
"""Regenerate assets/search-index.js from page headings.
Run from the repo root:  python3 tools/build-index.py
"""
import re, json, os

PAGES = [
    ("index.html", "Overview"),
    ("prd.html", "PRD"),
    ("architecture.html", "Architecture"),
    ("data-model.html", "Data & API"),
    ("roadmap.html", "Roadmap"),
]

def strip_tags(s):
    s = re.sub(r'<span class="section-num">.*?</span>', '', s, flags=re.S)
    s = re.sub(r'<[^>]+>', '', s)
    for a, b in [('&amp;','&'),('&lt;','<'),('&gt;','>'),('&quot;','"'),('&#39;',"'"),('&nbsp;',' ')]:
        s = s.replace(a, b)
    return re.sub(r'\s+', ' ', s).strip()

def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    items = []
    for f, page in PAGES:
        html = open(os.path.join(root, f), encoding='utf-8').read()
        main_m = re.search(r'<main>(.*?)</main>', html, flags=re.S)
        body = main_m.group(1) if main_m else html
        for m in re.finditer(r'<h([23])\s+id="([a-z0-9-]+)"[^>]*>(.*?)</h\1>', body, flags=re.S):
            title = strip_tags(m.group(3))
            if not title:
                continue
            # capture only this section's own prose — stop at the next heading,
            # otherwise a section is searchable by text that belongs to a later one
            tail = body[m.end():]
            nxt = re.search(r'<h[23]\s+id=', tail)
            if nxt:
                tail = tail[:nxt.start()]
            items.append({
                "p": page, "f": f, "h": m.group(2),
                "t": title, "lv": int(m.group(1)),
                "k": strip_tags(tail)[:900],
            })
    out = ("/* Generated by tools/build-index.py — do not edit by hand. */\n"
           "window.NOBEL_INDEX = " + json.dumps(items, ensure_ascii=False, separators=(',', ':')) + ";\n")
    open(os.path.join(root, "assets/search-index.js"), "w", encoding='utf-8').write(out)
    print(f"wrote assets/search-index.js — {len(items)} entries")

if __name__ == "__main__":
    main()
